package com.example.model

import android.content.Context
import android.util.Log
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.security.MessageDigest

/**
 * Describes one language's real, on-device STT model as shipped in assets/models.
 * Every field here is read from model_manifest.json, which is regenerated by
 * tools/model_conversion/convert_stt.py whenever a language pack is (re)built —
 * nothing here is fabricated or estimated.
 */
data class SttModelAsset(
    val id: String,
    val name: String,
    val architecture: String,
    val sourceModel: String,
    val onnxExport: String,
    val modelType: String,
    val modelPath: String,
    val tokensPath: String,
    val sampleRateHz: Int,
    val featureDim: Int,
)

data class TtsModelAsset(
    val id: String,
    val name: String,
    val acousticModelPath: String,
    val vocoderPath: String,
    val frontendConfigPath: String,
    val sampleRateHz: Int,
)

data class LanguagePack(
    val code: String,
    val englishName: String,
    val stt: SttModelAsset?,
    val tts: TtsModelAsset?,
)

data class VadModelAsset(
    val id: String,
    val name: String,
    val modelPath: String,
    val sampleRateHz: Int,
    val windowSizeSamples: Int,
)

/**
 * File-level facts about one asset actually present on disk: real size and a real
 * SHA-256 computed by streaming the file (never loaded fully into memory, since
 * STT models can be 100MB+). This is informational/debug-only — Android's own APK
 * signature check is what actually guarantees these bytes weren't tampered with;
 * we don't keep a separate "expected hash" to compare against.
 */
data class VerifiedAsset(
    val path: String,
    val sizeBytes: Long,
    val sha256: String,
)

/**
 * Loads and exposes the real, data-driven language-pack manifest under
 * assets/models/model_manifest.json. A language only appears fully "ready" once
 * both its STT and TTS assets are present — see [isLanguageSttReady] /
 * [isLanguageTtsReady]. New languages are added purely by dropping converted
 * model files into assets and adding a manifest entry; no code changes needed.
 */
class BundledModelManager(private val context: Context) {

    private val _vadModel = MutableStateFlow<VadModelAsset?>(null)
    val vadModel: StateFlow<VadModelAsset?> = _vadModel.asStateFlow()

    private val _languagePacks = MutableStateFlow<Map<String, LanguagePack>>(emptyMap())
    val languagePacks: StateFlow<Map<String, LanguagePack>> = _languagePacks.asStateFlow()

    private val _isManifestLoaded = MutableStateFlow(false)
    val isManifestLoaded: StateFlow<Boolean> = _isManifestLoaded.asStateFlow()

    // IndicSttEngine and IndicTtsEngine share one BundledModelManager but each calls
    // loadAndVerifyBundledModels() from its own init{} — this makes the second call a
    // cheap no-op instead of re-parsing the manifest and re-hashing every model file.
    private val loadStarted = java.util.concurrent.atomic.AtomicBoolean(false)
    private val loadCompleted = kotlinx.coroutines.CompletableDeferred<Unit>()

    private val _verifiedAssets = MutableStateFlow<Map<String, VerifiedAsset>>(emptyMap())
    val verifiedAssets: StateFlow<Map<String, VerifiedAsset>> = _verifiedAssets.asStateFlow()

    // SHA-256 verification is informational only (shown as "verified" badges on the
    // Settings screen) — Android's APK signature check is what actually guarantees the
    // bytes weren't tampered with, see [VerifiedAsset]. It must never gate real model
    // loading, so it runs on its own long-lived scope instead of inside
    // loadAndVerifyBundledModels() — otherwise every caller (both STT's init-time
    // ensureModelsForLanguage() and TTS's first speak()) sat blocked behind hashing
    // several GB across every bundled language before the ONE language actually needed
    // could even start loading, which is what made first use of TTS/STT feel frozen on
    // real hardware.
    private val verificationScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    suspend fun loadAndVerifyBundledModels() {
        if (!loadStarted.compareAndSet(false, true)) {
            loadCompleted.await()
            return
        }
        withContext(Dispatchers.IO) {
        try {
            val manifestJson = context.assets.open("models/model_manifest.json")
                .bufferedReader().use { it.readText() }
            val root = JSONObject(manifestJson)

            val vadObj = root.optJSONObject("vad")
            _vadModel.value = vadObj?.let {
                VadModelAsset(
                    id = it.getString("id"),
                    name = it.getString("name"),
                    modelPath = it.getString("file"),
                    sampleRateHz = it.getInt("sampleRateHz"),
                    windowSizeSamples = it.getInt("windowSizeSamples"),
                )
            }

            val languagesObj = root.getJSONObject("languages")
            val packs = mutableMapOf<String, LanguagePack>()
            for (langCode in languagesObj.keys()) {
                val langObj = languagesObj.getJSONObject(langCode)
                val sttObj = langObj.optJSONObject("stt")
                val ttsObj = langObj.optJSONObject("tts")

                packs[langCode] = LanguagePack(
                    code = langCode,
                    englishName = langObj.optString("englishName", langCode),
                    stt = sttObj?.let {
                        SttModelAsset(
                            id = it.getString("id"),
                            name = it.getString("name"),
                            architecture = it.getString("architecture"),
                            sourceModel = it.getString("sourceModel"),
                            onnxExport = it.getString("onnxExport"),
                            modelType = it.getString("modelType"),
                            modelPath = it.getString("model"),
                            tokensPath = it.getString("tokens"),
                            sampleRateHz = it.getInt("sampleRateHz"),
                            featureDim = it.getInt("featureDim"),
                        )
                    },
                    tts = ttsObj?.let {
                        TtsModelAsset(
                            id = it.getString("id"),
                            name = it.getString("name"),
                            acousticModelPath = it.getString("acoustic"),
                            vocoderPath = it.getString("vocoder"),
                            frontendConfigPath = it.getString("frontend"),
                            sampleRateHz = it.getInt("sampleRateHz"),
                        )
                    },
                )
            }
            _languagePacks.value = packs
            _isManifestLoaded.value = true
        } catch (e: Exception) {
            Log.e("BundledModelManager", "Error loading model manifest", e)
            _isManifestLoaded.value = false
        }
        }
        // Unblock every caller (model loading included) as soon as the manifest itself
        // is parsed — that's a few KB of JSON, not the multi-GB asset set below.
        loadCompleted.complete(Unit)

        val packs = _languagePacks.value
        if (packs.isEmpty()) return

        verificationScope.launch {
            try {
                // Verify (real size + real SHA-256, streamed) every asset the manifest
                // actually references, so the Settings screen shows facts, not fiction.
                val toVerify = mutableListOf<String>()
                _vadModel.value?.let { toVerify += it.modelPath }
                packs.values.forEach { pack ->
                    pack.stt?.let { toVerify += listOf(it.modelPath, it.tokensPath) }
                    pack.tts?.let { toVerify += listOf(it.acousticModelPath, it.vocoderPath, it.frontendConfigPath) }
                }
                // Hash every referenced asset concurrently rather than one at a time — with
                // 9+ languages that's several GB of model files, and streaming SHA-256 over
                // them sequentially on a single core was turning first-launch verification
                // into a multi-minute stall on real hardware.
                val verified = coroutineScope {
                    toVerify.map { path -> async { path to verifyAsset(path) } }
                        .awaitAll()
                        .mapNotNull { (path, asset) -> asset?.let { path to it } }
                        .toMap()
                }
                _verifiedAssets.value = verified

                Log.i(
                    "BundledModelManager",
                    "Verified ${verified.size}/${toVerify.size} bundled assets on disk (background)"
                )
            } catch (e: Exception) {
                Log.e("BundledModelManager", "Error verifying bundled assets", e)
            }
        }
    }

    private fun verifyAsset(assetPath: String): VerifiedAsset? {
        return try {
            val digest = MessageDigest.getInstance("SHA-256")
            var totalBytes = 0L
            context.assets.open("models/$assetPath").use { stream ->
                val buffer = ByteArray(1 shl 16)
                while (true) {
                    val read = stream.read(buffer)
                    if (read < 0) break
                    digest.update(buffer, 0, read)
                    totalBytes += read
                }
            }
            val hex = digest.digest().joinToString("") { "%02x".format(it) }
            VerifiedAsset(path = assetPath, sizeBytes = totalBytes, sha256 = hex)
        } catch (e: Exception) {
            Log.w("BundledModelManager", "Asset missing or unreadable: models/$assetPath (${e.message})")
            null
        }
    }

    fun isLanguageSttReady(code: String): Boolean = _languagePacks.value[code]?.stt != null
    fun isLanguageTtsReady(code: String): Boolean = _languagePacks.value[code]?.tts != null
}
